### ISSUE TITLE
TODO: sophisticated cognates identification

### ISSUE THREAD

**Issue by oserikov** [NIS-2018-CROSS-M/cross-lingual-morph-analysis#7]
- [X] align word embeddings
- [ ] create bilingual dictionaries
- [ ] create semantic clusters
- [ ] learn transliteration
- [ ] transliterate semantic clusters
- [ ] extract cognate clusters from semantic clusters
- [ ] merge into calma/cognates-boost branch

**Comment by erba994** [comment]
@oserikov can I take over on this indipendently or it is a dead-end and should be removed?
